<?php

declare(strict_types=1);

namespace OLScPanel\Services;

use OLScPanel\Utils\Logger;
use OLScPanel\Config\ConfigManager;
use OLScPanel\Models\Domain;
use OLScPanel\Models\SslCertificate;

class OpenLiteSpeedService
{
    private Logger $logger;
    private ConfigManager $config;
    private string $olsHome;
    private string $olsConfigFile;

    public function __construct(Logger $logger, ConfigManager $config, string $olsHome = '/usr/local/lsws')
    {
        $this->logger = $logger;
        $this->config = $config;
        $this->olsHome = $olsHome;
        $this->olsConfigFile = $olsHome . '/conf/httpd_config.conf';
    }

    public function isRunning(): bool
    {
        $output = shell_exec('systemctl is-active lshttpd 2>/dev/null');
        return trim($output) === 'active';
    }

    public function start(): bool
    {
        $this->logger->info('Starting OpenLiteSpeed');
        
        $result = shell_exec('systemctl start lshttpd 2>&1');
        $exitCode = shell_exec('echo $?');

        if (trim($exitCode) === '0') {
            $this->logger->info('OpenLiteSpeed started successfully');
            return true;
        } else {
            $this->logger->error('Failed to start OpenLiteSpeed', [
                'output' => $result,
                'exit_code' => $exitCode
            ]);
            return false;
        }
    }

    public function stop(): bool
    {
        $this->logger->info('Stopping OpenLiteSpeed');
        
        $result = shell_exec('systemctl stop lshttpd 2>&1');
        $exitCode = shell_exec('echo $?');

        if (trim($exitCode) === '0') {
            $this->logger->info('OpenLiteSpeed stopped successfully');
            return true;
        } else {
            $this->logger->error('Failed to stop OpenLiteSpeed', [
                'output' => $result,
                'exit_code' => $exitCode
            ]);
            return false;
        }
    }

    public function restart(): bool
    {
        $this->logger->info('Restarting OpenLiteSpeed');
        
        $result = shell_exec('systemctl restart lshttpd 2>&1');
        $exitCode = shell_exec('echo $?');

        if (trim($exitCode) === '0') {
            $this->logger->info('OpenLiteSpeed restarted successfully');
            return true;
        } else {
            $this->logger->error('Failed to restart OpenLiteSpeed', [
                'output' => $result,
                'exit_code' => $exitCode
            ]);
            return false;
        }
    }

    public function reload(): bool
    {
        $this->logger->info('Reloading OpenLiteSpeed configuration');
        
        $result = shell_exec('systemctl reload lshttpd 2>&1');
        $exitCode = shell_exec('echo $?');

        if (trim($exitCode) === '0') {
            $this->logger->info('OpenLiteSpeed reloaded successfully');
            return true;
        } else {
            $this->logger->error('Failed to reload OpenLiteSpeed', [
                'output' => $result,
                'exit_code' => $exitCode
            ]);
            return false;
        }
    }

    public function generateConfiguration(array $domains): bool
    {
        $this->logger->info('Generating OpenLiteSpeed configuration', [
            'domain_count' => count($domains)
        ]);

        try {
            $config = $this->generateBaseConfig();
            $config .= $this->generateListeners($domains);
            $config .= $this->generateVirtualHosts($domains);
            $config .= $this->generatePhpHandlers($domains);

            if (!file_put_contents($this->olsConfigFile, $config)) {
                throw new \RuntimeException("Failed to write configuration file: {$this->olsConfigFile}");
            }

            $this->logger->info('OpenLiteSpeed configuration generated successfully', [
                'config_file' => $this->olsConfigFile
            ]);

            return true;

        } catch (\Exception $e) {
            $this->logger->error('Failed to generate OpenLiteSpeed configuration', [
                'error' => $e->getMessage()
            ]);
            return false;
        }
    }

    private function generateBaseConfig(): string
    {
        $serverConfig = $this->config->getServerConfig();
        $performanceConfig = $this->config->getPerformanceConfig();
        $securityConfig = $this->config->getSecurityConfig();

        $config = "# OpenLiteSpeed Configuration generated by OLS cPanel\n";
        $config .= "# Generated at: " . date('Y-m-d H:i:s') . "\n\n";

        $config .= "serverName {$serverConfig['name']}\n";
        $config .= "user {$serverConfig['user']}\n";
        $config .= "group {$serverConfig['group']}\n";
        $config .= "adminEmails {$serverConfig['admin_email']}\n";
        $config .= "priority 0\n";
        $config .= "autoRestart 1\n";
        $config .= "gracefulRestartTimeout 300\n";
        $config .= "indexFiles index.html, index.php\n\n";

        $config .= $this->generateErrorLogConfig();
        $config .= $this->generateAccessLogConfig();
        $config .= $this->generateTuningConfig($performanceConfig);
        $config .= $this->generateSecurityConfig($securityConfig);

        return $config;
    }

    private function generateErrorLogConfig(): string
    {
        $loggingConfig = $this->config->getLoggingConfig();
        
        $config = "errorlog logs/error.log {\n";
        $config .= "    logLevel {$loggingConfig['level']}\n";
        $config .= "    rollingSize {$loggingConfig['max_log_size_mb']}M\n";
        $config .= "    enableStderrLog 1\n";
        $config .= "}\n\n";

        return $config;
    }

    private function generateAccessLogConfig(): string
    {
        $loggingConfig = $this->config->getLoggingConfig();
        
        $config = "accessLog logs/access.log {\n";
        $config .= "    rollingSize {$loggingConfig['max_log_size_mb']}M\n";
        $config .= "    keepDays {$loggingConfig['retention_days']}\n";
        $config .= "    compressArchive 1\n";
        $config .= "    logReferer 1\n";
        $config .= "    logUserAgent 1\n";
        $config .= "}\n\n";

        return $config;
    }

    private function generateTuningConfig(array $performanceConfig): string
    {
        $config = "tuning {\n";
        $config .= "    maxConnections {$performanceConfig['max_connections']}\n";
        $config .= "    maxSSLConnections {$performanceConfig['max_ssl_connections']}\n";
        $config .= "    connTimeout 300\n";
        $config .= "    maxKeepAliveReq {$performanceConfig['max_keep_alive_requests']}\n";
        $config .= "    keepAliveTimeout {$performanceConfig['keep_alive_timeout']}\n";
        $config .= "    maxReqURLLen 32768\n";
        $config .= "    maxReqHeaderSize 65536\n";
        $config .= "    maxReqBodySize 2047M\n";
        $config .= "    maxDynRespSize 2047M\n";
        $config .= "    enableGzipCompress " . ($performanceConfig['gzip_compression'] ? '1' : '0') . "\n";
        $config .= "    gzipCompressLevel {$performanceConfig['gzip_level']}\n";
        $config .= "    enableBrCompress 4\n";
        $config .= "    quicEnable 1\n";
        $config .= "    quicShmDir /dev/shm\n";
        $config .= "}\n\n";

        return $config;
    }

    private function generateSecurityConfig(array $securityConfig): string
    {
        $config = "accessDenyDir {\n";
        $config .= "    dir /\n";
        $config .= "    dir /etc/*\n";
        $config .= "    dir /dev/*\n";
        $config .= "    dir conf/*\n";
        $config .= "    dir admin/conf/*\n";
        $config .= "}\n\n";

        $config .= "fileAccessControl {\n";
        $config .= "    followSymbolLink 1\n";
        $config .= "    checkSymbolLink 0\n";
        $config .= "    requiredPermissionMask 000\n";
        $config .= "    restrictedPermissionMask 000\n";
        $config .= "}\n\n";

        $config .= "perClientConnLimit {\n";
        $config .= "    staticReqPerSec 0\n";
        $config .= "    dynReqPerSec 0\n";
        $config .= "    outBandwidth 0\n";
        $config .= "    inBandwidth 0\n";
        $config .= "    softLimit 10000\n";
        $config .= "    hardLimit 10000\n";
        $config .= "    gracePeriod 15\n";
        $config .= "    banPeriod 300\n";
        $config .= "}\n\n";

        return $config;
    }

    private function generateListeners(array $domains): string
    {
        $config = "";
        $hasSsl = false;

        foreach ($domains as $domainData) {
            if ($domainData['ssl_certificate']) {
                $hasSsl = true;
                break;
            }
        }

        $config .= "listener http {\n";
        $config .= "    address *:80\n";
        $config .= "    secure 0\n";
        $config .= "    map {$this->olsHome}/conf/vhosts/*.conf\n";
        $config .= "}\n\n";

        if ($hasSsl) {
            $config .= "listener https {\n";
            $config .= "    address *:443\n";
            $config .= "    secure 1\n";
            $config .= "    keyFile {$this->olsHome}/conf/ssl/default.key\n";
            $config .= "    certFile {$this->olsHome}/conf/ssl/default.crt\n";
            $config .= "    map {$this->olsHome}/conf/vhosts/*.conf\n";
            $config .= "}\n\n";
        }

        return $config;
    }

    private function generateVirtualHosts(array $domains): string
    {
        $config = "";
        $vhostDir = $this->olsHome . '/conf/vhosts';

        if (!is_dir($vhostDir)) {
            mkdir($vhostDir, 0755, true);
        }

        foreach ($domains as $domainData) {
            $domain = $domainData['domain'];
            $vhostConfig = $this->generateVirtualHostConfig($domainData);
            $vhostFile = $vhostDir . '/' . $domain . '.conf';

            file_put_contents($vhostFile, $vhostConfig);

            $config .= "include {$vhostFile}\n";
        }

        return $config . "\n";
    }

    private function generateVirtualHostConfig(array $domainData): string
    {
        $domain = $domainData['domain'];
        $user = $domainData['user'];
        $documentRoot = $domainData['document_root'];
        $phpVersion = $domainData['php_version'];
        $sslCert = $domainData['ssl_certificate'];

        $config = "virtualHost {$domain} {\n";
        $config .= "    vhRoot {$documentRoot}\n";
        $config .= "    configFile {$this->olsHome}/conf/vhosts/{$domain}.xml\n";
        $config .= "    allowSymbolLink 1\n";
        $config .= "    enableScript 1\n";
        $config .= "    restrained 0\n";
        $config .= "    user {$user}\n";
        $config .= "    group {$user}\n";
        $config .= "}\n\n";

        $config .= $this->generateVirtualHostXml($domainData);

        return $config;
    }

    private function generateVirtualHostXml(array $domainData): string
    {
        $domain = $domainData['domain'];
        $documentRoot = $domainData['document_root'];
        $phpVersion = $domainData['php_version'];
        $sslCert = $domainData['ssl_certificate'];

        $xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        $xml .= "<virtualHost>\n";
        $xml .= "    <hostName>{$domain}</hostName>\n";
        
        if (isset($domainData['subdomains'])) {
            foreach ($domainData['subdomains'] as $subdomain) {
                $xml .= "    <hostName>{$subdomain['domain']}</hostName>\n";
            }
        }

        $xml .= "    <aliases></aliases>\n";
        $xml .= "    <member>{$domainData['user']}</member>\n";
        $xml .= "    <docRoot>{$documentRoot}</docRoot>\n";
        $xml .= "    <enableGzip>1</enableGzip>\n";
        $xml .= "    <enableBr>1</enableBr>\n";

        $xml .= "    <context>\n";
        $xml .= "        <type>server</type>\n";
        $xml .= "        <uri>/</uri>\n";
        $xml .= "        <location>{$documentRoot}</location>\n";
        $xml .= "        <allowOverride>1</allowOverride>\n";
        $xml .= "    </context>\n";

        $xml .= "    <context>\n";
        $xml .= "        <type>lsapi</type>\n";
        $xml .= "        <uri>\\.php$</uri>\n";
        $xml .= "        <note>PHP {$phpVersion}</note>\n";
        $xml .= "        <addType>application/x-httpd-php</addType>\n";
        $xml .= "        <handler>lsapi{$phpVersion}</handler>\n";
        $xml .= "    </context>\n";

        if ($sslCert && !$sslCert->isSelfSigned()) {
            $xml .= "    <ssl>\n";
            $xml .= "        <keyFile>{$this->olsHome}/conf/ssl/{$domain}.key</keyFile>\n";
            $xml .= "        <certFile>{$this->olsHome}/conf/ssl/{$domain}.crt</certFile>\n";
            $xml .= "        <caFile>{$this->olsHome}/conf/ssl/{$domain}.ca</caFile>\n";
            $xml .= "        <certChain>1</certChain>\n";
            $xml .= "        <enableECDHE>1</enableECDHE>\n";
            $xml .= "        <renegProtection>1</renegProtection>\n";
            $xml .= "        <sslProtocol>30</sslProtocol>\n";
            $xml .= "        <ciphers>ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384</ciphers>\n";
            $xml .= "    </ssl>\n";

            $this->writeSslFiles($domain, $sslCert);
        }

        $xml .= "</virtualHost>\n";

        return $xml;
    }

    private function generatePhpHandlers(array $domains): string
    {
        $phpVersions = [];
        foreach ($domains as $domainData) {
            $phpVersions[] = $domainData['php_version'];
        }
        $phpVersions = array_unique($phpVersions);

        $config = "";
        foreach ($phpVersions as $version) {
            $config .= $this->generatePhpHandler($version);
        }

        return $config;
    }

    private function generatePhpHandler(string $version): string
    {
        $phpBinary = $this->getPhpBinary($version);
        
        $config = "extprocessor lsapi{$version} {\n";
        $config .= "    type lsapi\n";
        $config .= "    address uds://tmp/lshttpd/lsapi{$version}.sock\n";
        $config .= "    maxConns 35\n";
        $config .= "    env PHP_LSAPI_CHILDREN=35\n";
        $config .= "    env LSAPI_AVOID_FORK=1\n";
        $config .= "    initTimeout 60\n";
        $config .= "    retryTimeout 0\n";
        $config .= "    persistConn 1\n";
        $config .= "    respBuffer 0\n";
        $config .= "    autoStart 1\n";
        $config .= "    path {$phpBinary}\n";
        $config .= "    backlog 50\n";
        $config .= "    instances 1\n";
        $config .= "    priority 0\n";
        $config .= "    memSoftLimit 2047M\n";
        $config .= "    memHardLimit 2047M\n";
        $config .= "    procSoftLimit 400\n";
        $config .= "    procHardLimit 500\n";
        $config .= "}\n\n";

        return $config;
    }

    private function getPhpBinary(string $version): string
    {
        $possiblePaths = [
            // cPanel EA-PHP paths (priority)
            "/opt/cpanel/ea-php{$version}/bin/php",
            // System PHP paths
            "/usr/bin/php{$version}",
            "/usr/local/bin/php{$version}",
            // Alternative paths
            "/usr/bin/php",
            "/usr/local/bin/php"
        ];

        foreach ($possiblePaths as $path) {
            if (file_exists($path)) {
                return $path;
            }
        }

        return "/usr/bin/php";
    }

    private function writeSslFiles(string $domain, SslCertificate $certificate): void
    {
        $sslDir = $this->olsHome . '/conf/ssl';
        if (!is_dir($sslDir)) {
            mkdir($sslDir, 0755, true);
        }

        file_put_contents($sslDir . '/' . $domain . '.key', $certificate->getPrivateKey());
        file_put_contents($sslDir . '/' . $domain . '.crt', $certificate->getCertificate());
        file_put_contents($sslDir . '/' . $domain . '.ca', $certificate->getCaBundle());

        chmod($sslDir . '/' . $domain . '.key', 0600);
        chmod($sslDir . '/' . $domain . '.crt', 0644);
        chmod($sslDir . '/' . $domain . '.ca', 0644);
    }

    public function validateConfiguration(): array
    {
        $errors = [];

        if (!file_exists($this->olsConfigFile)) {
            $errors[] = 'OpenLiteSpeed configuration file not found';
            return $errors;
        }

        $output = shell_exec("{$this->olsHome}/bin/lswsctrl -t -c {$this->olsConfigFile} 2>&1");
        $exitCode = shell_exec('echo $?');

        if (trim($exitCode) !== '0') {
            $errors[] = 'Configuration syntax error: ' . $output;
        }

        return $errors;
    }

    public function getVersion(): string
    {
        $output = shell_exec("{$this->olsHome}/bin/lswsctrl -v 2>/dev/null");
        if ($output && preg_match('/(\d+\.\d+\.\d+)/', $output, $matches)) {
            return $matches[1];
        }
        return 'unknown';
    }

    public function getServerStatus(): array
    {
        $status = [
            'running' => $this->isRunning(),
            'version' => $this->getVersion(),
            'uptime' => $this->getUptime(),
            'connections' => $this->getConnections(),
            'memory_usage' => $this->getMemoryUsage(),
            'cpu_usage' => $this->getCpuUsage()
        ];

        return $status;
    }

    private function getUptime(): string
    {
        $output = shell_exec("{$this->olsHome}/bin/lswsctrl status 2>/dev/null");
        if ($output && preg_match('/Uptime:\s*(.+)/', $output, $matches)) {
            return trim($matches[1]);
        }
        return 'unknown';
    }

    private function getConnections(): array
    {
        $connections = [
            'total' => 0,
            'active' => 0,
            'ssl' => 0
        ];

        $output = shell_exec("{$this->olsHome}/bin/lswsctrl status 2>/dev/null");
        if ($output) {
            if (preg_match('/Total Connections:\s*(\d+)/', $output, $matches)) {
                $connections['total'] = (int)$matches[1];
            }
            if (preg_match('/Active Connections:\s*(\d+)/', $output, $matches)) {
                $connections['active'] = (int)$matches[1];
            }
            if (preg_match('/SSL Connections:\s*(\d+)/', $output, $matches)) {
                $connections['ssl'] = (int)$matches[1];
            }
        }

        return $connections;
    }

    private function getMemoryUsage(): array
    {
        $memory = [
            'used' => 0,
            'total' => 0,
            'percentage' => 0
        ];

        $pid = $this->getLshttpdPid();
        if ($pid) {
            $output = shell_exec("ps -p {$pid} -o rss,vsz 2>/dev/null | tail -1");
            if ($output && preg_match('/(\d+)\s+(\d+)/', $output, $matches)) {
                $memory['used'] = (int)$matches[1] * 1024; // Convert KB to bytes
                $memory['total'] = (int)$matches[2] * 1024;
                $memory['percentage'] = $memory['total'] > 0 ? ($memory['used'] / $memory['total']) * 100 : 0;
            }
        }

        return $memory;
    }

    private function getCpuUsage(): float
    {
        $pid = $this->getLshttpdPid();
        if ($pid) {
            $output = shell_exec("ps -p {$pid} -o %cpu 2>/dev/null | tail -1");
            if ($output) {
                return (float)trim($output);
            }
        }

        return 0.0;
    }

    private function getLshttpdPid(): ?string
    {
        $output = shell_exec('pgrep -f lshttpd 2>/dev/null');
        return $output ? trim($output) : null;
    }
}
